# Generated by Django 3.0.3 on 2020-03-14 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='sqft',
            new_name='sqrt',
        ),
    ]
